""" What is this?  This is a human made list of mathematical abbreviations (which was created by manually browsing through the titles of PM nodes and writing down any abbreviations of words that were used or came immediately to mind).  We know the abbreviations are reasonable since we made it ourselves.  This first list only contains SINGLE WORDS.  There are no phrases such as 'finitely generated': 'f.g.'.  The second list only contains PHRASES.  That is, more than one word as the key.
"""

word_to_abbr = {
	'linear': 'lin',
	'independent': 'ind',
	'separable': 'sep',
	'element': 'elt',
	'bilinear': 'bilin',
	'alternating': 'alt',
	'external': 'ext',
	'direct': 'dir',
	'group': 'gp',
	'theorem': 'thm',
	'lemma': 'lem',
	'corollary': 'cor',
	'definition': 'def',
	'proof': 'pf',
	'remark': 'rmk',
	'property': 'prop',
	'isomorphism': 'iso',
	'homomorphism': 'hom',
	'monomorphism': 'mono',
	'bijection': 'bij',
	'endomorphism': 'endo',
	'interior': 'int',
	'integer': 'int',
	'generator': 'gen',
	'ring': 'R',
	'field': 'F',
	'rationals': 'Q',
	'integers': 'Z',
	'rank': 'rk',
	'elementary': 'elem',
	'algorithm': 'algo',
	'kernel': 'kern',
	'sequence': 'seq',
	'minimum': 'min',
	'minimal': 'minl',
	'maximum': 'max\'',
	'maximal': 'max\'l',
	'fundamental': 'fund',
	'invariant': 'inv',
	'characteristic': 'char',
	'eigenvalue': 'eval',
	'finite': 'fin',
	'polynomial': 'poly',
	'prime': 'p',
	'irreducible': 'irr',
	'degree': 'deg',
	'order': 'ord',
	'algebraic': 'alg',
	'diagonal': 'diag',
	'equivalent': 'equiv',
	'Galois': 'Gal',
	'similar': 'sim',
	'multiple': 'mult',
	'multiply': 'mult',
	'divisor': 'div',
	'divides': 'div',
}

phrase_to_abbr = {
	'principal ideal domain': 'PID',
	'integral domain': 'ID',
	'euclidean domain': 'ED',
	'finitely generated': 'fg',
	'tensor product': 'tprod',
	'rational canonical form': 'RCF',
	'jordan canonical form': 'JCF',
	'smith normal form': 'SNF',
	'such that': 's.t.',
}
