"""  This is a list of mathematical abbreviations taken from Wikipedia.  That is, from https://en.wikipedia.org/wiki/List_of_mathematical_abbreviations

A few things had multiple abbreviations, so I just wrote "# or other abbreviation" next to the main abbr.
"""

key_to_abbr = {
	'Axiom of Choice': 'AC',
	'absolute continuity': 'a.c.',
	'absolutely continuous': 'a.c.',
	'inverse chord': 'acrd',
	'adjugate matrix': 'adj',
	'adjugate': 'adj',
	'almost everywhere': 'a.e.',
	'Airy': 'Ai', # or Bi
	'Action limit': 'AL',
	'alternating group': 'Alt',
	'arithmetic mean': 'A.M.',
	'inverse cosine': 'arccos',
	'inverse cosecant': 'arccosec',
	'inverse cotangent': 'arccot',
	'inverse cosecant': 'arccsc',
	'inverse excosecant': 'arcexc',
	'inverse excosecant': 'arcexcosec',
	'inverse excosecant': 'arcexcsc',
	'inverse exsecant': 'arcexs',
	'inverse exsecant': 'arcexsec',
	'inverse hyperbolic cosecant': 'arcosech',
	'inverse hyperbolic cosine': 'arcosh',
	'inverse hyperbolic cotangent': 'arcoth',
	'inverse hyperbolic cosecant': 'arcsch',
	'inverse secant': 'arcsec',
	'inverse sine': 'arcsin',
	'inverse tangent': 'arctan',
	'inverse tangent with two arguments': 'arctan2', # or atan2
	'argument': 'arg',
	'argument of the maximum': 'arg max',
	'argument of the minimum': 'arg min',
	'inverse hyperbolic secant': 'arsech',
	'inverse hyperbolic sine': 'arsinh',
	'inverse hyperbolic tangent': 'artanh',
	'almost surely': 'a.s.',
	'arithmetic progression': 'A.P.',
	'automorphism group': 'Aut',
	'boundary': 'bd', # or fr
	'bias of an estimator': 'Bias',
	'cardinality': 'Card',
	'cumulative distribution function': 'cdf',
	'cumulative frequency': 'c.f.',
	'characteristic': 'char',
	'hyperbolic cosine integral': 'Chi',
	'cosine integral': 'Ci',
	'cos + i sin': 'cis', # or expi
	'conjugacy class': 'Cl',
	'closure': 'cl',
	'codomain': 'cod', # or codom
	'cokernel': 'cok', # or coker
	'convex hull': 'conv',
	'corollary': 'Cor',
	'correlation': 'corr',
	'cosine': 'cos',
	'cosecant': 'cosec',
	'hyperbolic cosecant': 'cosech',
	'hyperbolic cosine': 'cosh',
	'coversine': 'cosiv',
	'cotangent': 'cot',
	'hyperbolic cotangent': 'coth',
	'covariance': 'cov',
	'coversine': 'cover',
	'covercosine': 'covercos',
	'coversine': 'covers',
	'chord': 'crd',
	'cosecant': 'csc',
	'hyperbolic cosecant': 'csch',
	'cotangent': 'ctg',
	'curl': 'curl',
	'covercosine': 'cvc',
	'coversine': 'cvs',
	'define': 'def',
	'degree of a polynomial': 'deg',
	'del': 'del',
	'determinant': 'det',
	'dimension': 'dim',
	'divergence': 'div',
	'decalitre': 'dkl',
	'does not exist': 'DNE',
	'domain': 'dom',
	'endomorphisms': 'End',
	'exponential integral': 'Ei',
	'epigraph': 'epi',
	'equation': 'Eqn',
	'error function': 'erf',
	'complementary error function': 'erfc',
	'exponent of the trace': 'etr',
	'excosecant': 'exc', # or excosec or excsc
	'exsecant': 'exsec', # or exs
	'exponential': 'exp',
	'exponential minus 1': 'expm1',
	'exponential minus 1': 'exp1m',
	'Ext functor': 'Ext',
	'exterior': 'ext',
	'extreme point': 'extr',
	'finite intersection property': 'FIP',
	'first-order logic': 'FOL',
	'Frobenius endomorphism': 'Frob',
	'Galois group': 'Gal',
	'greatest common divisor': 'gcd',
	'Gudermannian': 'gd',
	'Galois field': 'GF',
	'general linear group': 'GL',
	'geometric mean': 'G.M.',
	'greatest lower bound': 'glb',
	'geometric progression': 'G.P.',
	'gradient': 'grad',
	'hacoversine': 'hacover',
	'hacovercosine': 'hacovercos',
	'hacoversine': 'hacovers',
	'haversine': 'hav',
	'havercosine': 'havercos',
	'hacovercosine': 'hcc',
	'hacoversine': 'hcv',
	'highest common factor': 'hcf',
	'harmonic mean': 'H.M.',
	'higher-order logic': 'HOL',
	'Hom functor': 'Hom',
	'hom-class': 'hom',
	'H': 'hot',
	'Collatz conjecture': 'HOTPO',
	'Half Or Triple Plus One': 'HOTPO',
	'havercosine': 'hvc',
	'hypograph': 'hyp',
	'if and only if': 'iff',
	'I': 'IH',
	'independent and identically distributed random variables': 'iid',
	'imaginary part': 'Im',
	'image': 'im',
	'infimum': 'inf',
	'interior': 'int',
	'kernel': 'ker',
	'binary logarithm': 'lb',
	'lowest common multiple': 'lcm',
	'binary logarithm': 'ld',
	'linear interpolation': 'lerp',
	'common logarithm': 'lg',
	'left-hand side': 'LHS',
	'offset logarithmic integral': 'Li',
	'logarithmic integral': 'li',
	'limit': 'lim',
	'limit inferior': 'lim inf',
	'limit superior': 'lim sup',
	'natural logarithm': 'ln',
	'natural logarithm plus 1': 'lnp1',
	'natural logarithm plus 1': 'ln1p',
	'logarithm': 'log',
	'natural logarithm': 'logh',
	'first-order language': 'LST',
	'language': 'LST',
	'least upper bound': 'lub',
	'maximum': 'max',
	'mathematical induction': 'M.I.',
	'minimum': 'min',
	'modular arithmetic': 'mod',
	'modulo': 'mod',
	'metaplectic group': 'Mp',
	'modified hyperbolic tangent': 'mtanh',
	'modified hyperbolic tangent': 'mth',
	'matrix': 'mx',
	'Sheffer stroke': 'NAND',
	'not-and': 'NAND',
	'number': 'No.',
	'Logical NOR|not-or': 'NOR',
	'need to show': 'NTS',
	'object class': 'ob'
	'ordinal number': 'ord',
	'probability density function': 'pdf',
	'proof': 'pf'
	'projective general linear group': 'PGL',
	'pin group': 'Pin',
	'probability mass function': 'pmf',
	'probability of an event': 'Pr', # or P
	'projective special linear group': 'PSL',
	'projective orthogonal group': 'PSO',
	'projective special unitary group': 'PSU',
	'projective unitary group': 'PU',
	'Quod erat demonstrandum': 'QED',
	'quod erat faciendum': 'QEF',
	'range': 'ran',
	'rank': 'rk', # or rank
	'real part': 'Re',
	'respectively.': 'resp'
	'right-hand side': 'RHS',
	'root mean square': 'RMS', # or rms
	'non-unital ring': 'rng',
	'rot (mathematics)|rotor': 'rot',
	'required to prove.': 'RTP'
	'Random Variable': 'RV',
	'standard deviation': 'SD',
	'standard error': 'SE',
	'secant': 'sec'
	'hyperbolic secant': 'sech',
	'initial segment': 'seg',
	'haversine': 'sem',
	'strong finite intersection property': 'SFIP',
	'signum': 'sgn',
	'sign': 'sgn',
	'hyperbolic sine integral': 'Shi'
	'sine integral': 'Si',
	'sine': 'sin',
	'Sinc': 'sinc',
	'hyperbolic sine': 'sinh',
	'versine': 'siv',
	'special linear group': 'SL',
	'special orthogonal group': 'SO',
	'solution': 'Soln'
	'symplectic group': 'Sp',
	'linear span': 'sp',
	'spectrum of a ring': 'Spec',
	'spin group': 'Spin',
	'such that': 's.t.',
	'standard part': 'st',
	'sufficient to prove': 'STP',
	'special unitary group': 'SU ',
	'supremum': 'sup',
	'support': 'supp',
	'symmetric group': 'Sym',
	'tangent': 'tan', # or tg or tgn
	'hyperbolic tangent': 'tanh',
	'the following are equivalent.': 'TFAE'
	'theorem': 'Thm',
	'Tor functor': 'Tor',
	'trace': 'Tr'
	'`ed': 'undef'
	'volume': 'v',
	'variance': 'var',
	'vercosine': 'vcs',
	'versine': 'ver',
	'vercosine': 'vercos',
	'versine': 'vers',
	'which was what we wanted': 'W^5',
	'without any loss of generality': 'walog',
	'well-formed formula': 'wff',
	'with high probability.': 'whp'
	'without loss of generality': 'wlog',
	'we may assume.': 'WMA'
	'well-ordered': 'WO',
	'w': 'wp1',
	'with respect to': 'wrt',
	'want to prove.': 'WTP'
	'want to show.': 'WTS'
	'exclusive or': 'XOR',
	'Zermelo–Fraenkel axioms': 'ZFC', # or ZF
}
